<?php
/**
 * @file
 * Code for the GSB Feature Research Paper Display feature.
 */

include_once 'gsb_feature_research_paper_display.features.inc';

/**
 * Implements hook_entity_info_alter()
 *
 */

function gsb_feature_research_paper_display_entity_info_alter(&$entity_info)
{
  $entity_info['field_collection_item']['view modes']['research_pager'] = array(
    'label' => t('Research Pager'),
    'custom settings' => TRUE,
  );

}



// Formatter

/**
 * Implements hook_field_formatter_info().
 *
 */
function gsb_feature_research_paper_display_field_formatter_info()
{
  return array(
    'gsb_research_papers_formatter' => array(
      'label' => t('Field Collection for Research Papers'),
      'field types' => array('text'),
      'settings' => array('view_mode' => 'research_pager'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function gsb_feature_research_paper_display_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display)
{
  if ($display['type'] == 'gsb_research_papers_formatter' && ($display['settings']['view_mode'] == 'research_pager' || $display['settings']['view_mode'] == 'case_study')) {
    $element = array();
    $name = "";
    $name .= @$entity->field_first_name['und'][0]['value'];
    $name .= ' ' . @$entity->field_last_name['und'][0]['value'];
    if (!empty($entity->field_person_fac_student_ref))
      $element[] = array(
        '#type' => 'link',
        '#href' => "taxonomy/term/" . $entity->field_person_fac_student_ref['und'][0]['target_id'],
        '#title' => $name,
        '#options' => array(
          'html' => TRUE,
        ),
        '#attributes' => array(
          'class' => array(
            'linked-author',
          ),
        ),
      );
    else
      $element[] = array(
        '#type' => 'markup',
        '#markup' => $name,
      );
    return $element;
  }
}
/**
 * Implements hook_form_FORM_ID_alter() for views_exposed_form().
 */
function gsb_feature_research_paper_display_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form_state['view']->name == 'research_paper_filters') {
    // Exclude the search text field from auto-submit.
    $form['search']['#attributes']['class'][] = 'ctools-auto-submit-exclude';
  }
}
